---
- name: Create Sandbox
  hosts: localhost

  tasks:
    - name: Include secrets
      include_vars: "{{ playbook_dir }}/secrets.yml"

    - name: Include import
      include_vars: "{{ playbook_dir }}/import.yml"

    - name: Create EC2s
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        count: 3
        group_id: sg-9f705be4
        image: "{{ ami }}"
        instance_profile_name: ec2_read
        instance_type: t2.micro
        key_name: aws
        region: "{{ region }}"
        wait: yes
      register: sandbox

    - name: Tag Alpha
      ec2_tag:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        resource: "{{ sandbox.instances[0].id }}"
        state: present
        tags:
          Name: ALPHA
          Type: sandbox

    - name: Tag Bravo
      ec2_tag:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        resource: "{{ sandbox.instances[1].id }}"
        state: present
        tags:
          Name: BRAVO
          Type: sandbox

    - name: Tag Charlie
      ec2_tag:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        resource: "{{ sandbox.instances[2].id }}"
        state: present
        tags:
          Name: CHARLIE
          Type: sandbox

#    - name: EC2 Details
#      debug: msg="{{ sandbox | json_query('instances[*].public_ip') }}"

    - name: Write hosts file
      vars:
        contents: "ALPHA\t{{ sandbox.instances[0].public_ip }}\nBRAVO\t{{ sandbox.instances[1].public_ip }}\nCHARLIE\t{{ sandbox.instances[2].public_ip }}\n"
      copy:
        content: "{{ contents }}"
        dest: "{{ playbook_dir }}/hosts"

    - name: Create target group
      add_host:
        name: "{{ item }}"
        groups: target
        ansible_user: ec2-user
      with_items:
        - "{{ sandbox| json_query('instances[*].public_ip') }}"

    - name: Wait for ssh
      wait_for:
        host: "{{ item }}"
        port: 22
        state: started
      with_items:
        - "{{ sandbox| json_query('instances[*].public_ip') }}"

- name: Update EC2s
  hosts: target

  tasks:
    - name: Include import
      include_vars: "{{ playbook_dir }}/import.yml"

    - name: Ping
      ping:

    - name: Copy files
      copy:
        dest: "/app/{{ item }}"
        group: "{{ user }}"
        mode: 0644
        owner: "{{ user }}"
        src: "{{ playbook_dir }}/{{ item }}"
      with_items:
        - hosts
        - assignment.txt
      become: yes
      become_user: root

    - name: Touch log files
      vars:
        now: "{{ lookup('pipe', 'date +%Y%m%d%H%M') }}"
      file:
        group: "{{ user }}"
        mode: 0644
        owner: "{{ user }}"
        path: "/log/{{ item }}"
        state: touch
      with_items:
        - error_log
        - access_log
        - shakespeare-romeo-48.txt
      become: yes
      become_user: root

    - name: Touch old log files
      vars:
        yesterday: "{{ lookup('pipe', 'date +%Y%m%d -d \"1 day ago\"') }}2359"
        twodaysago: "{{ lookup('pipe', 'date +%Y%m%d -d \"2 day ago\"') }}2359"
        threedaysago: "{{ lookup('pipe', 'date +%Y%m%d -d \"3 day ago\"') }}2359"
      shell: touch -t {{ item.time }} {{ item.file }}; chown {{ user }}:{{ user }} {{ item.file }}
      with_items:
        - { file: 'access_log.1240921107', time: "{{ yesterday }}" }
        - { file: 'access_log.3408210027', time: "{{ twodaysago }}" }
        - { file: 'access_log.3423032082', time: "{{ threedaysago }}" }
      become: yes
      become_user: root

    - name: Chmod  644 /app/* and /log/*
      shell: chmod 644 {{ item }}/*
      with_items:
        - /app
        - /log
      become: yes
      become_user: root

    - name: Chmod  644 /app/* and /log/*
      shell: chmod 644 {{ item }}/*
      with_items:
        - /app
        - /log
      become: yes
      become_user: root

- name: Pring hosts
  hosts: localhost

  tasks:
    - name: Print hosts
      vars:
        msg: 
          - "alpha: {{ groups['target'][0] }}"
          - "bravo: {{ groups['target'][1] }}"
          - "charlie: {{ groups['target'][2] }}"
      debug: msg="{{ msg }}"
...
